[package]
name = "metrics_evaluation"
version = "0.1.0"
edition = "2021"

[lib]
name = "puzzle"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.53"
chrono = "0.4.19"
humantime = "2.1.0"
nom = "7.1.0"
parse-hyperlinks = "0.23.3"
cfg-if = "1.0.0"

# Async-Deps
tokio = { version = "1.16.1", features = ["rt", "macros"], optional = true }
tokio-test = "0.4.2"
async-trait = { version = "0.1.52", optional = true }
async-recursion = { version = "1.0.0", optional = true }

[features]
default = ["async", "hashmap"]
hashmap = []
async = ["tokio", "async-trait", "async-recursion"]
